### ISSUE TITLE
loads of orphans + half block reward

### ISSUE THREAD

**Issue by coinnodenl** [sammy007/open-ethereum-pool#175]
This is weird... see : http://etc-pool.ethereumminer.eu/#/blocks

I have already updates my etc geth but still getting loads of orphans en half blocks meaning its to slow?

**Comment by rsoares21** [comment]
How many peers connected ?

**Comment by coinnodenl** [comment]
48 so that should be sufficient.. It is pool software issue not geth.

**Comment by mikeyb** [comment]
more likely your server and not the software @coinnodenl

**Comment by rsoares21** [comment]
Try closing geth and pool. Then run geth, wait until it syncs then run pool again.

**Comment by alterdev** [comment]
I encounter same issue. 
I did not use this pool long. a week and a half i think ... but in the beginning i was mining only blocks. Since a week ago i am mining only orphans and uncles. **ONLY** 
I have the pool on ETC, updated geth to latest Ethereum Classic Geth 3.5.86, no change, Server should have been ok, i made no changes on it. About 40 computers linked to the pool. 
Can anyone understand what has happened? It seems to be something with ETC. Does it happen also on ETH pools? 
Have a great day guys and thx for all your help.

**Comment by coinnodenl** [comment]
I quess it has something to do with the lower block awards?

**Comment by coinnodenl** [comment]
http://gastracker.io/miner/0xa6501146ae5f3f369dca4acc911c1edb2667bffe No good

**Comment by sony87** [comment]
I had the same issue, fixed it with migration to Parity, runs perfect now.

**Comment by coinnodenl** [comment]
Started installing parity aswell, will let you know the outcome

**Comment by alterdev** [comment]
Started Parity on classic chain and it did improve the situation. Thx all, all the best

**Comment by coinnodenl** [comment]
Parity does the trick!
