### ISSUE TITLE
Unable to process payouts: invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type common.Address

### ISSUE THREAD

**Issue by voipcall** [sammy007/open-ethereum-pool#237]
Redis version: Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

OS & Version: Ubuntu 16.04

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour
Error: Unable to process payouts: invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type common.Address

````

**Comment by kulibih** [comment]
+1

**Comment by mikeyb** [comment]
@voipcall try including the requested information that is necessary. PS, the error is obvious.


See all the stuff below you decided to delete and not include expecting strangers to know what software your computer is running?  Yeah, well we don't.  So if you want help, help us help you.


Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour


#### Actual behaviour


#### Steps to reproduce the behaviour


#### Backtrace

````
[backtrace]
````

**Comment by kulibih** [comment]
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-101-generic x86_64)
Parity/v1.8.2-beta-1b6588c-20171025/x86_64-linux-gnu/rustc1.21.0
redis-server --version
Redis server v=4.0.2 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=147238c324de8b19
 Unable to process payouts: Invalid params: invalid length 1, expected a 0x-prefixed, padded, hex-encoded hash with length 40.
2017/12/01 09:56:04 Paid total 0 Shannon to 0 of 1 payees

**Comment by kulibih** [comment]
127.0.0.1:6379[1]> ZREVRANGE "eth:payments:pending" 0 -1 WITHSCORES
(empty list or set)

**Comment by mikeyb** [comment]
And if you use a non beta parity client?

P.S.

https://github.com/sammy007/open-ethereum-pool/issues/156
https://github.com/sammy007/open-ethereum-pool/issues/104

My guess is latest parity drops 0x prefix so when the pool software goes to handle the address it fails because there is no proper hex prefix.  Does it output what address it is trying to pay out to in debug logging?

My guess it is related to https://github.com/sammy007/open-ethereum-pool/issues/232

Probably want to drop to a lower parity version that doesnt implement the changes until the pool is updated

**Comment by kulibih** [comment]
Gdbix/v1.5.3-fluxdbix-f6911ea5/linux/go1.8.3
and
Parity/v1.8.2-beta-1b6588c-20171025/x86_64-linux-gnu/rustc1.21.0
kul@vm2:~$ geth version
Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9

**Comment by kulibih** [comment]
welkom teamviewer   584 135 878 pass 376xdt

**Comment by kulibih** [comment]
https://github.com/ethereum/go-ethereum/commit/b33a5294eaf06a3e952efe1ce4ef810af37d1062

can be problematic because of this

**Comment by voipcall** [comment]
@kulibih , is it solution for a problem ?
How i can fix in my case? I am using https://github.com/Musicoin/go-musicoin

**Comment by mikeyb** [comment]
That is a fix in geth, ask parity to fix it

**Comment by voipcall** [comment]
@mikeyb, how i can fix geth in my https://github.com/Musicoin/go-musicoin?
I don't know

**Comment by kulibih** [comment]
config pay.json
// Address with pool balance
    "address": "0x0*******************************",

Work

**Comment by voipcall** [comment]
@kulibih, i don't have file pay.json

**Comment by voipcall** [comment]
ok, thank you
