### ISSUE TITLE
when i build ember, it occur errors: no such file or directory blablabla jquery.cookie.js

### ISSUE THREAD

**Issue by wudics** [sammy007/open-ethereum-pool#296]
How can i fix this error?

**Comment by mvilera** [comment]
There's a format that you should use to open issues, if not it will be really hard for anyone to even try to figure out your problem.

**Comment by wudics** [comment]
what is the format i should use?

**Comment by mvilera** [comment]
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour


#### Actual behaviour


#### Steps to reproduce the behaviour


#### Backtrace

````
[backtrace]
````

**Comment by mikeyb** [comment]
Lol, when one search for `ember` in this repo could have fixed your issue.  You have now waited 4+ days for help you don't need on an issue that isn't and issue.

[derp](https://github.com/sammy007/open-ethereum-pool/search?q=ember&type=Issues&utf8=%E2%9C%93)

P.S. Your submitted issue still sucks, contains no info, and will likely be closed.  I wish your users the best of luck, they are going to need it.
