### ISSUE TITLE
Site is not loading

### ISSUE THREAD

**Issue by Marow** [sammy007/open-ethereum-pool#376]
What is the Problem when the Site doesnt load?

the /api/stats is available and can be read, but the site nothing.
If i search the site code, it only shows that:

`<body class="ember-application">
    <div id="app">
      
    </div>
</body>`

But why?
This problem comes from nothing... the pool was working before

Can i see log anywhere or something?

**Comment by mikeyb** [comment]
This isnt tech support for your blunders.  We dont know what you broke, especially since you are too good to gill out the issue template.  Instead deleting it and putting useless requests in here.

#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour


#### Actual behaviour


#### Steps to reproduce the behaviour


#### Backtrace

````
[backtrace]
````

**Comment by Marow** [comment]
It was my fail. I dont know why the pool works over 1 year with that.

enviroments.js i set the port after the domain. Now kick that out and works.
