### ISSUE TITLE
Miner problem

### ISSUE THREAD

**Issue by djsmoke2018** [sammy007/open-ethereum-pool#378]
when i get my mine i have the following problem.
what could be the reason

Received unknown response: {"method":"mining.notify","params":["33e22161","a96eee00a231888b98495a903083a5c4c8ce6edcc6f9c24361396ba901363c74","43b5b154c8b46b749fe5e7c7d5ff408e8b33f46833c192741e3b4eb5fba8d8b7",true],"id":null}

ETH: 08/12/18-17:14:57 - SHARE FOUND - (GPU 0)
ETH: Share rejected (31 ms)!

**Comment by mikeyb** [comment]
No clue.  Nobody has any idea of your setup because you thought you would take it upon yourself to delete the requested information when you created this issue.  Go help yourself if you are too good to fill out a few pieces of information.

In case you missed the big blob of text you deleted before submitting a useless issue, here is another copy:
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour


#### Actual behaviour


#### Steps to reproduce the behaviour


#### Backtrace

````
[backtrace]
````

**Comment by mikeyb** [comment]
Actually, I answered you already IN YOUR OTHER ISSUE.. Stop opening issues!!!

https://github.com/sammy007/open-ethereum-pool/issues/368#issuecomment-410450169

**Comment by mikeyb** [comment]
For anyone not tech savvy.  I will install a dockerized mining pool for you.  The cost is $300 paid in crypto for the setup and $100/hour for any work outside of installation and setup.

**Comment by djsmoke2018** [comment]
I have already solved this problem. #368 (comment) That's why I closed it.
What I have now is miner problem.

just forget about it. i will try to solve the problem myself.

**Comment by mikeyb** [comment]
Actually, this problem is directly related to the last problem.  Your problem is Parity.  This issue tracker is not for supporting your mining software, obviously.

**Comment by djsmoke2018** [comment]
i reinstalled after the last problem. parity and pool functioning. blockchain is currently in the pool. 

i tried to install Nice hash from https://github.com/wfr/open-ethereum-pool-nh but will uninstall it now.

thanks for your help anyway.
