### ISSUE TITLE
balance problem

### ISSUE THREAD

**Issue by mdikmetas** [sammy007/open-ethereum-pool#418]
Immature Balance: 0.00000000
Pending Balance: 0.00000000
Credited coins awaiting payout.
 Total Paid: 0.00000000

but im find 10 block i cant see why?

**Comment by mikeyb** [comment]
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour


#### Actual behaviour


#### Steps to reproduce the behaviour


#### Backtrace

````
[backtrace]
````

**Comment by mdikmetas** [comment]
im sory but thank you all information. im realy newbie but im read read read now not problem install and any problem

i try ballzcoin

geth version 1.8.12 stable dc65e60d

redis server v=3.0.6

what is Backtrace?

**Comment by mdikmetas** [comment]
now 17 block 

balance 0

**Comment by mdikmetas** [comment]
my error thank you
