### ISSUE TITLE
no longer works out the box - unpinned nested dependencies hard to debug

### ISSUE THREAD

**Issue by 1blockologist** [sammy007/open-ethereum-pool#453]
#### System information

Geth version: Geth/v1.9.10-stable-58cf5686/linux-amd64/go1.13.6

Redis version: Redis server v=5.0.5 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=8babad91eba747dd

OS & Version: Linux Ubuntu 19.10

Commit branch and hash: master, bcfc0eb

#### Expected behaviour

running ./build/bin/open-ethereum-pool config.json allows for http access to a dashboard showing stats from geth and stratum mining instructions and information about workers

#### Actual behaviour

accessing the webserver at port 80 shows either a blank page with just the footer, or a page that says STATS API DOWN, and reading other musings online show that this is just the precursor to other errors

on the console the logs and similar complaints around the net for an infinitely repeating:

Can't parse pending block number
Error while refreshing pending block on main: strconv.ParseUint: parsing "": invalid syntax

One solution is to manually download someone's obscure dependency from a gitter chatroom "intl-format-cache" and replace it in the node_modules of the www folder. and then sudo npm install? or do you just skip that and go to ./build.sh again? have fun with that

also this does not solve the aforementioned problems, and it isn't clear if the environment.js file is incorrect, or the config.json file in the root project folder is incorrect

so this is all a bit dated but is the only game in town, with the issues with the dependencies exacerbating all of it, making it very difficult to debug

#### Steps to reproduce the behaviour

follow the instructions in the readme and various outdated blogs. mess around with IP addresses and ports for a while, google the error messages and unexpected behavior, go to gitter chatroom for community support and "clues" because nobody knows the answer and then come here.

unpinned dependencies undermine the utility of mentioning the environment at all, because any version could be installed on user's system given the point in time it occurred meaning reproducibility is limited.

will try to install with every package stuck at a certain old version

**Comment by drhashes** [comment]
One problem you are having could be:

geth 1.9.10 no longer works with the master branch of the pool, see
https://github.com/ethereum/go-ethereum/pull/20460
Also parity changed the rpc communication protocol a long time ago..

You could try the previous geth version to see if that clears up the error "Error while refreshing pending block on main: strconv.ParseUint: parsing "": invalid syntax"

To really fix it, you should try the develop branch of the pool. It should work with parity and probably with the latest geth (untested).

This wont fix your problem with web pages though since those are due to entirely different reasons.

EDIT:
According to this post the geth people will revert to the old behavior in the next version of geth. Then the master branch of the pool will work again.
https://github.com/ethereum/go-ethereum/issues/20587

**Comment by 1blockologist** [comment]
> This wont fix your problem with web pages though since those are due to entirely different reasons.

so what is the fix for that

**Comment by 1blockologist** [comment]
this is not maintained, ended up messing around with various forks and customizations
