### ISSUE TITLE
Unlocker crash

### ISSUE THREAD

**Issue by rastko1996** [sammy007/open-ethereum-pool#62]
Hello, I have an issue with unlocker. It crashes almost after every new block that comes, it's really annoying having stuck blocks in the pool, and I have to restart it every time. Are there any known causes for this and solutions? 
The error it crashes with is in the attachment

![screenshot-20160805-15 02 51](https://cloud.githubusercontent.com/assets/8715031/17440932/43f80c4c-5b1e-11e6-8376-50a5fa8d4142.png)

**Comment by phylusM** [comment]
I ran into this issue as well.  For me geth was timing out on the eth_getBlockByNumber call.  Sometimes it would take 5 seconds, sometimes 2 minutes.  Honestly, I recently built the parity branch of the pool and started using parity built from their master branch since geth has been a headache for me.  It seems to be running fine so far.

**Comment by sammy007** [comment]
Where is a crash here? If your geth times out it's in bad shape and must not be used for payouts processing or block unlocking while it's in bad shape. This is a reason why I halt unlocker and payments in case of any error received.

**Comment by sammy007** [comment]
> I recently built the parity branch

Make sure you have disabled signer otherwise parity can lock whole RPC due to its single threaded RPC when you are using node for payouts. All details in wiki.
