### ISSUE TITLE
ubuntu 16.04 setup

### ISSUE THREAD

**Issue by sademat** [sammy007/open-ethereum-pool#87]
hi ,

I want to build open-Etherium-pool but I do not know how to configure.

could you tell how you're doing ngnix.conf and other configurations.

thanks.

**Comment by boysie123** [comment]
The steps for setting up ngnix are very poor and vague and without lots of knowledge to interpret the instructions it seems impossible to setup.

all I end up with is Stats API Temporarily Down, and I have no idea if its the ngnix config or some thing else.

If either some one can paste the json config layout that would help a lot.

thanks

Boysie

**Comment by mikeyb** [comment]
Running a pool is a **very** technical undertaking.  It should not be easy to comprehend without prior knowledge of the technologies being used, this just leads to pools being run by people who don't know how or why certain things happen, which leads to very negative perception of the service you are trying to render.

NGINX has some amazing documentation, and when you understand NGINX the issues you are referring to are trivial.

You should also be very comfortable debugging and looking at logs, something I rarely see anyone here with an issue doing.  All I see is "Tell me how to make it work".  Instead what should be seen is "I tried this action, which gave me this result and after trying to figure out why I keep getting this result I am stuck on this specific part".

If this was a paid software, sure I would expect hand holding.  But this is free software with no warranty, use it at your own risk.  I personally would never use a pool created by someone who doesn't understand basic web services like nginx, or how to read a log file to see why something is happening.

I for one and glad this pool is not obvious to setup, it keeps the technically challenged from putting out crappy services on the web.  It appears you just joined github today, which tells me you are just here to make money and not provide a valuable service. If you wanted to provide a valuable service you would take the time to understand the technologies being used.  If this pool was that hard to setup, nobody would be running open ethereum pool, but there are hundreds of pools running it which tells me those with an acceptable level of understanding have no problem setting up the software.

**Comment by LeChuckDE** [comment]
@mikeyb WOW now i am flashed, 
someone think and says the same like I do the hole time !
If you don't get the setup working, troubleshoot basics, solve problems, 
then you are not ready to publish your own pool !

BTW. If you want a own pool, 
there are some serviceproviders that offer the services to host and support your pool-instance, 
Sure it isn't for free. For such services there is a monthly fee and also a setup fee.
It isn't cheap but you got a full service with 24/7 monitoring at Highperformance Server-Farm.

I am such a Provider as example, but there are others too.
At time hosting roundabout 12 different Dagger-Hashimoto based pools and 10 other pools.

(and there is no way to do not pay the 10 % developer-fee to sammy[10% from your profit], 
at own setup there is a choice to setup donation or not, at my hosted pools it is a basic to support the main-developer! all other things are a nogo !)
Pls be aware open-source isn't "it's for free !"

**Comment by boysie123** [comment]
my issue turned out to not be the config but the config at the time of running build.sh, I finally found you hard code into the client side js the api end point so fixing it in the config makes no change really, you have to rebuild the site, logical really but knowing is always key. 

you are right people shouldn't think they can pick up free code they do not understand and run a half understood half cooked  pool and fail at the first problem.

I do stand by my original comment about the instruction. Dev's and codes shouldn't write user manuals or install instruction, when they clearly lack the technical skill to understand process and how to define steps leaving nothing to the imagination or guess work. I would offer to provide my service but I don't run a technical auth company :) and cant really be assed :) 

oh well now to work out how to get multiple front ends using the same redis cluster and db. unpicking this design is slow but enlightening on route.

**Comment by LeChuckDE** [comment]
@boysie123 it is build in to host more then one frontend at one server. the redis part will be splitted based on coinname like in config file describbed 
if you will provide more the one api over one server you have to modify code to use differen api addresses each coin

**Comment by boysie123** [comment]
arh yes wrong end of the stick, I mean 2 front end web servers each hosting the same pool of the same  coin with a load balancer and having them display the same info, not sure if need sticky sessions across all ports/80/8008/8080 but currently when I set this up I end up with 2 different pools and I cant work out ...mainly due to lack of redis skills how its storing its data and get them to both use the same data. any pointers?

**Comment by boysie123** [comment]
I did that but still the data seems to be separate. I built a redis cluster and pointed them both at the cluster same config settings same ip same port, but the fount ends seem to work as separate pools...

**Comment by stone212** [comment]
@boysie123 said:

>  I finally found you hard code into the client side js the api end point so fixing it in the config makes no change really

Can you explain what you mean by this?  Where did you hard code it?

> Dev's and codes shouldn't write user manuals or install instruction, when they clearly lack the ... skill to understand process and how to define steps

Absolutely true!  I already offered to do this for this project but only got some childish replies.  Possibly I will anyway now that no one is maintaining it.

**Comment by mikeyb** [comment]
@stone212 dont lie.  You severely lack the knowledge to run this.  The kicker is, it doesn't need instructions when you know what you are doing.  If you don't know what you are doing **YOU SHOULD NOT BE RUNNING A POOL, IT WILL FAIL**

**Comment by sammy007** [comment]
Agree with @mikeyb if somebody is good in CS:GO it does not mean he is capable to run financial services.
